### ISSUE TITLE
Deployment through now button does not work.

### ISSUE THREAD

**Issue by alexedev** [pranaygp/zeit-deployments#1]
1. Clicked the NOW button in repo readme.
2. In ZEIT account created new API TOKEN and copied secret to clipboard.
3. Pasted secret to both ZEIT API TOKEN and NOW_API_KEY.
4. clicked DEPLOY button.
5. Initialising... takes about a minute.
![screen shot 2017-01-30 at 12 19 41](https://cloud.githubusercontent.com/assets/1526837/22421217/6ae1026a-e6e6-11e6-9206-e3267feabb4c.png)
6. Error: Deploy failed, please check the repo and try again.
![screen shot 2017-01-30 at 12 17 33](https://cloud.githubusercontent.com/assets/1526837/22421148/2529eb1a-e6e6-11e6-967a-77cd28198c23.png)

**Comment by pranaygp** [comment]
Thanks for reporting this @alexedev 

It's been fixed in release 1.0.1
